import { useEffect, useState, type ReactNode } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useServerFn } from '@tanstack/react-start';
import { Fuel, Loader2, Pencil, Plus, Trash2, Truck, Wrench } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ModuleTabs } from '@/components/module-tabs';
import { useCompany } from '@/lib/company-context';
import { getFleetWorkspace, saveFleetAsset, saveFuelRecord, saveMaintenanceRecord, deleteFleetRecord, type FleetAsset, type FuelRecord, type MaintenanceRecord } from '@/lib/fleet.functions';
import { fleetMetrics } from '@/lib/fleet-metrics';

type Draft = { id?:string; name:string; code:string; kind:'vehicle'|'machine'|'implement'; plate:string; meter_unit:'km'|'h'; initial_meter:string; status:string; notes:string; asset_id:string; recorded_at:string; meter:string; liters:string; unit_price:string; full_tank:boolean; supplier:string; property_id:string; cost_center_id:string; season_id:string; description:string; scheduled_at:string; completed_at:string; next_meter:string; amount:string };
type Mode = 'asset'|'fuel'|'maintenance';
const blank = (mode:Mode):Draft=>({name:'',code:'',kind:'vehicle',plate:'',meter_unit:'km',initial_meter:'0',status:mode==='maintenance'?'scheduled':'active',notes:'',asset_id:'',recorded_at:'',meter:'',liters:'',unit_price:'',full_tank:false,supplier:'',property_id:'',cost_center_id:'',season_id:'',description:'',scheduled_at:'',completed_at:'',next_meter:'',amount:'0'});
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const number=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:2});
const day=(s:string)=>s.split('-').reverse().join('/');
const labels:Record<string,string>={active:'Ativo',inactive:'Inativo',scheduled:'Programada',completed:'Concluída',canceled:'Cancelada',vehicle:'Veículo',machine:'Máquina',implement:'Implemento'};
function Field({label,children}:{label:string;children:ReactNode}) {return <label className="min-w-0 space-y-1 text-xs text-muted-foreground"><span>{label}</span>{children}</label>;}

export function FleetWorkspace() {
 const {company,canCreate,canEdit,canDelete,canViewSubmodule}=useCompany();
 const client=useQueryClient(); const fetch=useServerFn(getFleetWorkspace); const saveAsset=useServerFn(saveFleetAsset); const saveFuel=useServerFn(saveFuelRecord); const saveMaintenance=useServerFn(saveMaintenanceRecord); const remove=useServerFn(deleteFleetRecord);
 const [editor,setEditor]=useState<{mode:Mode;draft:Draft}|null>(null); const [error,setError]=useState('');
 const [assetFilter,setAssetFilter]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState('');
 useEffect(()=>{setEditor(null);setError('');setAssetFilter('');},[company.id]);
 const query=useQuery({queryKey:['fleet',company.id],queryFn:()=>fetch({data:{companyId:company.id}}),enabled:Boolean(company.id)});
 const data=query.data; const assets=data?.assets??[]; const fuels=data?.fuel??[]; const maintenance=data?.maintenance??[];
 const success=()=>{setEditor(null);setError('');void client.invalidateQueries({queryKey:['fleet',company.id]});};
 const mutation=useMutation({mutationFn:async({mode,draft:d}:{mode:Mode;draft:Draft})=>{
  const identity={id:d.id,companyId:company.id};
  if(mode==='asset') return saveAsset({data:{...identity,name:d.name,code:d.code,kind:d.kind,plate:d.plate,meter_unit:d.meter_unit,initial_meter:Number(d.initial_meter),status:d.status==='inactive'?'inactive':'active',notes:d.notes}});
  const shared={...identity,asset_id:d.asset_id,meter:Number(d.meter),supplier:d.supplier,notes:d.notes,property_id:d.property_id||null,cost_center_id:d.cost_center_id||null,season_id:d.season_id||null};
  if(mode==='fuel') return saveFuel({data:{...shared,recorded_at:d.recorded_at,liters:Number(d.liters),unit_price:Number(d.unit_price),full_tank:d.full_tank}});
  return saveMaintenance({data:{...shared,description:d.description,scheduled_at:d.scheduled_at,completed_at:d.status==='completed'?d.completed_at:null,next_meter:d.next_meter?Number(d.next_meter):null,amount:Number(d.amount),status:d.status==='completed'?'completed':d.status==='canceled'?'canceled':'scheduled'}});
 },onSuccess:success,onError:(e:Error)=>setError(e.message)});
 const deletion=useMutation({mutationFn:({id,kind}:{id:string;kind:Mode})=>remove({data:{id,kind,companyId:company.id}}),onSuccess:success,onError:(e:Error)=>setError(e.message)});
 const set=(key:keyof Draft,value:string|boolean)=>setEditor(prev=>prev?{...prev,draft:{...prev.draft,[key]:value}}:null);
 const open=(mode:Mode,draft=blank(mode))=>{setError('');setEditor({mode,draft});};
 const within=(date:string)=>(!start||date>=start)&&(!end||date<=end);
 const assetName=(id:string)=>assets.find(a=>a.id===id)?.name??'—';
 const meterUnit=(id:string)=>assets.find(a=>a.id===id)?.meter_unit??'km';
 const editAsset=(r:FleetAsset)=>open('asset',{...blank('asset'),id:r.id,name:r.name,code:r.code,kind:r.kind as Draft['kind'],plate:r.plate,meter_unit:r.meter_unit as Draft['meter_unit'],initial_meter:String(r.initial_meter),status:r.status,notes:r.notes});
 const editFuel=(r:FuelRecord)=>open('fuel',{...blank('fuel'),id:r.id,asset_id:r.asset_id,recorded_at:r.recorded_at,meter:String(r.meter),liters:String(r.liters),unit_price:String(r.unit_price),full_tank:r.full_tank,supplier:r.supplier,notes:r.notes,property_id:r.property_id??'',cost_center_id:r.cost_center_id??'',season_id:r.season_id??''});
 const editMaintenance=(r:MaintenanceRecord)=>open('maintenance',{...blank('maintenance'),id:r.id,asset_id:r.asset_id,description:r.description,scheduled_at:r.scheduled_at,completed_at:r.completed_at??'',meter:String(r.meter),next_meter:r.next_meter===null?'':String(r.next_meter),amount:String(r.amount),status:r.status,supplier:r.supplier,notes:r.notes,property_id:r.property_id??'',cost_center_id:r.cost_center_id??'',season_id:r.season_id??''});
 const resource=(mode:Mode)=>`veiculos.${mode==='asset'?'fleet':mode}`;
 const actions=(id:string,mode:Mode,onEdit:()=>void)=><div className="flex shrink-0 gap-1">{canEdit(resource(mode))?<Button size="icon" variant="ghost" aria-label="Editar registro" title="Editar" onClick={onEdit}><Pencil className="h-4 w-4"/></Button>:null}{canDelete(resource(mode))?<Button size="icon" variant="ghost" aria-label="Excluir registro" title="Excluir" disabled={deletion.isPending} onClick={()=>{if(window.confirm('Excluir este registro?'))deletion.mutate({id,kind:mode});}}><Trash2 className="h-4 w-4"/></Button>:null}</div>;
 const input=(key:keyof Draft,type='text',required=false)=><input className="field-shell w-full text-sm" type={type} required={required} min={type==='number'?0:undefined} step={type==='number'?'0.001':undefined} value={String(editor?.draft[key]??'')} onChange={e=>set(key,e.target.value)}/>;
 const d=editor?.draft; const allowed=editor?(d?.id?canEdit(resource(editor.mode)):canCreate(resource(editor.mode))):false;
 const form=editor && d && allowed?<form className="space-y-4 border-y border-border/60 py-5" onSubmit={e=>{e.preventDefault();mutation.mutate(editor);}}>
  <h3 className="font-semibold">{d.id?'Editar':'Novo'} {editor.mode==='asset'?'veículo / máquina':editor.mode==='fuel'?'abastecimento':'registro de manutenção'}</h3>
  <div className="grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-3">
  {editor.mode==='asset'?<>
   <Field label="Nome">{input('name','text',true)}</Field><Field label="Código">{input('code','text',true)}</Field>
   <Field label="Tipo"><select className="field-shell w-full text-sm" value={d.kind} onChange={e=>set('kind',e.target.value)}><option value="vehicle">Veículo</option><option value="machine">Máquina</option><option value="implement">Implemento</option></select></Field>
   <Field label="Placa / identificação">{input('plate')}</Field><Field label="Medidor"><select className="field-shell w-full text-sm" value={d.meter_unit} onChange={e=>set('meter_unit',e.target.value)}><option value="km">Quilômetros (km)</option><option value="h">Horas (h)</option></select></Field><Field label="Leitura inicial">{input('initial_meter','number',true)}</Field>
   <Field label="Situação"><select className="field-shell w-full text-sm" value={d.status} onChange={e=>set('status',e.target.value)}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></Field>
  </>:<>
   <Field label="Veículo / máquina"><select className="field-shell w-full text-sm" required value={d.asset_id} onChange={e=>{const a=assets.find(r=>r.id===e.target.value);setEditor({...editor,draft:{...d,asset_id:e.target.value,meter:String(a?.initial_meter??0)}});}}><option value="">Selecione</option>{assets.filter(a=>a.status==='active'||a.id===d.asset_id).map(a=><option key={a.id} value={a.id}>{a.name} · {a.code}</option>)}</select></Field>
   <Field label={`Leitura (${meterUnit(d.asset_id)})`}>{input('meter','number',true)}</Field>
   {editor.mode==='fuel'?<><Field label="Data">{input('recorded_at','date',true)}</Field><Field label="Litros">{input('liters','number',true)}</Field><Field label="Preço por litro (R$)">{input('unit_price','number',true)}</Field><Field label="Total"><output className="field-shell block w-full text-sm text-foreground">{money(Number(d.liters)*Number(d.unit_price))}</output></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={d.full_tank} onChange={e=>set('full_tank',e.target.checked)}/>Tanque completo</label></>:<>
    <Field label="Serviço">{input('description','text',true)}</Field><Field label="Data programada">{input('scheduled_at','date',true)}</Field><Field label="Situação"><select className="field-shell w-full text-sm" value={d.status} onChange={e=>set('status',e.target.value)}><option value="scheduled">Programada</option><option value="completed">Concluída</option><option value="canceled">Cancelada</option></select></Field>{d.status==='completed'?<Field label="Data de conclusão">{input('completed_at','date',true)}</Field>:null}<Field label="Custo (R$)">{input('amount','number',true)}</Field><Field label="Próxima leitura">{input('next_meter','number')}</Field>
   </>}
   <Field label="Fornecedor / oficina">{input('supplier')}</Field>
   <Field label="Propriedade"><select className="field-shell w-full text-sm" value={d.property_id} onChange={e=>{set('property_id',e.target.value);set('season_id','');}}><option value="">Sem vínculo</option>{data?.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
   <Field label="Safra"><select className="field-shell w-full text-sm" value={d.season_id} onChange={e=>set('season_id',e.target.value)}><option value="">Sem vínculo</option>{data?.seasons.filter(s=>!d.property_id||s.property_id===d.property_id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>
   <Field label="Centro de custo"><select className="field-shell w-full text-sm" value={d.cost_center_id} onChange={e=>set('cost_center_id',e.target.value)}><option value="">Sem vínculo</option>{data?.centers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
  </>}
  <Field label="Observações"><textarea className="field-shell min-h-20 w-full text-sm" value={d.notes} onChange={e=>set('notes',e.target.value)}/></Field>
  </div><div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="outline" disabled={mutation.isPending} onClick={()=>setEditor(null)}>Cancelar</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?<Loader2 className="h-4 w-4 animate-spin"/>:null}Salvar</Button></div>
 </form>:null;
 const newButton=(mode:Mode,label:string)=>canCreate(resource(mode))?<Button variant="glow" className="max-w-full" disabled={mode!=='asset'&&!assets.some(a=>a.status==='active')} onClick={()=>open(mode)}><Plus className="h-4 w-4"/>{label}</Button>:null;
 const heading=(title:string,mode:Mode,label:string)=><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{title}</h2>{newButton(mode,label)}</div>;
 const empty=<p className="border-y border-border/60 py-8 text-center text-sm text-muted-foreground">Nenhum registro encontrado.</p>;
 const fleet=<div className="space-y-4">{heading('Frota e implementos','asset','Novo veículo')}{editor?.mode==='asset'?form:null}{assets.length?<div className="grid gap-3 lg:grid-cols-2">{assets.map(a=><article key={a.id} className="min-w-0 rounded-lg border border-border/60 bg-card/50 p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><Truck className="mb-2 h-5 w-5 text-primary"/><h3 className="break-words font-semibold">{a.name}</h3><p className="text-xs text-muted-foreground">{a.code} · {labels[a.kind]} · {labels[a.status]}</p></div>{actions(a.id,'asset',()=>editAsset(a))}</div><p className="mt-3 text-sm">{a.plate||'Sem placa'} · {number(Number(a.initial_meter))} {a.meter_unit} inicial</p></article>)}</div>:empty}</div>;
 const selectedFuel=fuels.filter(r=>(!assetFilter||r.asset_id===assetFilter)&&within(r.recorded_at)).slice().reverse();
 const fuel=<div className="space-y-4">{heading('Abastecimentos','fuel','Novo abastecimento')}{editor?.mode==='fuel'?form:null}{selectedFuel.length?<div className="divide-y divide-border/60">{selectedFuel.map(r=><article key={r.id} className="flex flex-wrap items-start justify-between gap-3 py-4"><div className="min-w-0"><h3 className="flex items-center gap-2 break-words font-medium"><Fuel className="h-4 w-4 shrink-0 text-primary"/>{assetName(r.asset_id)}</h3><p className="text-xs text-muted-foreground">{day(r.recorded_at)} · {number(Number(r.meter))} {meterUnit(r.asset_id)}{r.full_tank?' · Tanque completo':''}</p><p className="mt-2 text-sm">{number(Number(r.liters))} L × {money(Number(r.unit_price))} · {money(Number(r.total))}</p>{r.supplier?<p className="text-xs text-muted-foreground">{r.supplier}</p>:null}</div>{actions(r.id,'fuel',()=>editFuel(r))}</article>)}</div>:empty}</div>;
 const today=new Date().toLocaleDateString('en-CA');
 const selectedMaintenance=maintenance.filter(r=>(!assetFilter||r.asset_id===assetFilter)&&within(r.status==='completed'?r.completed_at??r.scheduled_at:r.scheduled_at));
 const service=<div className="space-y-4">{heading('Manutenção preventiva','maintenance','Nova manutenção')}{editor?.mode==='maintenance'?form:null}{selectedMaintenance.length?<div className="divide-y divide-border/60">{selectedMaintenance.map(r=>{const currentMeter=Math.max(Number(assets.find(a=>a.id===r.asset_id)?.initial_meter??0),...fuels.filter(f=>f.asset_id===r.asset_id).map(f=>Number(f.meter)),...maintenance.filter(m=>m.asset_id===r.asset_id&&m.status==='completed').map(m=>Number(m.meter)));const due=r.status==='scheduled'&&(r.scheduled_at<today||(r.next_meter!==null&&currentMeter>=Number(r.next_meter)));return <article key={r.id} className="flex flex-wrap items-start justify-between gap-3 py-4"><div className="min-w-0"><h3 className="flex items-center gap-2 break-words font-medium"><Wrench className="h-4 w-4 shrink-0 text-primary"/>{r.description}</h3><p className="text-xs text-muted-foreground">{assetName(r.asset_id)} · {day(r.scheduled_at)} · {labels[r.status]}</p>{due?<p className="mt-1 text-xs text-destructive">Manutenção pendente</p>:null}<p className="mt-2 text-sm">{money(Number(r.amount))}{r.next_meter!==null?` · Próxima: ${number(Number(r.next_meter))} ${meterUnit(r.asset_id)}`:''}</p>{r.completed_at?<p className="text-xs text-muted-foreground">Concluída em {day(r.completed_at)}</p>:null}</div>{actions(r.id,'maintenance',()=>editMaintenance(r))}</article>;})}</div>:empty}</div>;
 const metrics=fleetMetrics(assets.filter(a=>!assetFilter||a.id===assetFilter),fuels,maintenance,start,end);
 const costs=<div className="space-y-4"><h2 className="text-lg font-semibold">Consumo e custos</h2><div className="grid gap-4 border-y border-border/60 py-5 sm:grid-cols-3">{[['Combustível',metrics.reduce((s,r)=>s+r.fuelCost,0)],['Manutenção concluída',metrics.reduce((s,r)=>s+r.maintenanceCost,0)],['Custo total',metrics.reduce((s,r)=>s+r.total,0)]].map(([label,value])=><div key={String(label)} className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="mobile-value mt-1 text-xl font-semibold">{money(Number(value))}</p></div>)}</div>{metrics.length?<div className="grid gap-3 lg:grid-cols-2">{metrics.map(r=><article key={r.id} className="min-w-0 rounded-lg border border-border/60 p-4"><h3 className="break-words font-semibold">{r.name}</h3><dl className="mt-3 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-muted-foreground">Volume abastecido</dt><dd>{number(r.liters)} L</dd></div><div><dt className="text-xs text-muted-foreground">Custo total</dt><dd>{money(r.total)}</dd></div><div><dt className="text-xs text-muted-foreground">Uso medido</dt><dd>{r.distance===null?'—':`${number(r.distance)} ${r.meter_unit}`}</dd></div><div><dt className="text-xs text-muted-foreground">Custo / {r.meter_unit}</dt><dd>{r.costPerUnit===null?'—':money(r.costPerUnit)}</dd></div><div><dt className="text-xs text-muted-foreground">Consumo ({r.meter_unit==='km'?'km/L':'L/h'}) · tanque a tanque</dt><dd>{r.consumption===null?'—':number(r.consumption)}</dd></div></dl></article>)}</div>:empty}</div>;
 if(query.isLoading)return <div className="flex items-center gap-2 py-8 text-sm text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin text-primary"/>Carregando frota...</div>;
 if(query.error)return <div role="alert" className="space-y-3 text-sm text-destructive"><p>{query.error.message}</p><Button variant="outline" onClick={()=>void query.refetch()}>Tentar novamente</Button></div>;
 if(!['fleet','fuel','maintenance','costs'].some(s=>canViewSubmodule('veiculos',s)))return <p className="py-8 text-sm text-muted-foreground">Nenhum submódulo liberado para este acesso.</p>;
 return <div className="space-y-5">{error?<p role="alert" className="border border-destructive/40 bg-destructive/10 p-3 text-sm">{error}</p>:null}<div className="grid gap-3 sm:grid-cols-3"><Field label="Veículo / máquina"><select className="field-shell w-full text-sm" value={assetFilter} onChange={e=>setAssetFilter(e.target.value)}><option value="">Todos</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="De"><input className="field-shell w-full text-sm" type="date" value={start} max={end||undefined} onChange={e=>setStart(e.target.value)}/></Field><Field label="Até"><input className="field-shell w-full text-sm" type="date" value={end} min={start||undefined} onChange={e=>setEnd(e.target.value)}/></Field></div><ModuleTabs moduleSlug="veiculos" onValueChange={()=>setEditor(null)} tabs={[{value:'fleet',label:'Frota e implementos',content:fleet},{value:'fuel',label:'Abastecimentos',content:fuel},{value:'maintenance',label:'Manutenção',content:service},{value:'costs',label:'Consumo e custos',content:costs}]}/></div>;
}
