/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppComprasRouteImport } from './routes/app.compras'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppFolhaDePagamentoRouteImport } from './routes/app.folha-de-pagamento'
import { Route as AppFuncionariosRouteImport } from './routes/app.funcionarios'
import { Route as AppProducaoRouteImport } from './routes/app.producao'
import { Route as AppPropriedadesRouteImport } from './routes/app.propriedades'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppVeiculosRouteImport } from './routes/app.veiculos'
import { Route as AppVendasRouteImport } from './routes/app.vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFolhaDePagamentoRoute = AppFolhaDePagamentoRouteImport.update({
  id: '/folha-de-pagamento',
  path: '/folha-de-pagamento',
  getParentRoute: () => AppRoute,
} as any)
const AppFuncionariosRoute = AppFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppPropriedadesRoute = AppPropriedadesRouteImport.update({
  id: '/propriedades',
  path: '/propriedades',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosRoute = AppVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/folha-de-pagamento': typeof AppFolhaDePagamentoRoute
  '/app/funcionarios': typeof AppFuncionariosRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/propriedades': typeof AppPropriedadesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/vendas': typeof AppVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/folha-de-pagamento': typeof AppFolhaDePagamentoRoute
  '/app/funcionarios': typeof AppFuncionariosRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/propriedades': typeof AppPropriedadesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/vendas': typeof AppVendasRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/folha-de-pagamento': typeof AppFolhaDePagamentoRoute
  '/app/funcionarios': typeof AppFuncionariosRoute
  '/app/producao': typeof AppProducaoRoute
  '/app/propriedades': typeof AppPropriedadesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/vendas': typeof AppVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/empresas'
    | '/admin/usuarios'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/folha-de-pagamento'
    | '/app/funcionarios'
    | '/app/producao'
    | '/app/propriedades'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app/vendas'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/empresas'
    | '/admin/usuarios'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/folha-de-pagamento'
    | '/app/funcionarios'
    | '/app/producao'
    | '/app/propriedades'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app/vendas'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/empresas'
    | '/admin/usuarios'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/folha-de-pagamento'
    | '/app/funcionarios'
    | '/app/producao'
    | '/app/propriedades'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app/vendas'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compras': {
      id: '/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas': {
      id: '/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/folha-de-pagamento': {
      id: '/app/folha-de-pagamento'
      path: '/folha-de-pagamento'
      fullPath: '/app/folha-de-pagamento'
      preLoaderRoute: typeof AppFolhaDePagamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funcionarios': {
      id: '/app/funcionarios'
      path: '/funcionarios'
      fullPath: '/app/funcionarios'
      preLoaderRoute: typeof AppFuncionariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/producao': {
      id: '/app/producao'
      path: '/producao'
      fullPath: '/app/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propriedades': {
      id: '/app/propriedades'
      path: '/propriedades'
      fullPath: '/app/propriedades'
      preLoaderRoute: typeof AppPropriedadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos': {
      id: '/app/veiculos'
      path: '/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AppVeiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppComprasRoute: typeof AppComprasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFolhaDePagamentoRoute: typeof AppFolhaDePagamentoRoute
  AppFuncionariosRoute: typeof AppFuncionariosRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppPropriedadesRoute: typeof AppPropriedadesRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVeiculosRoute: typeof AppVeiculosRoute
  AppVendasRoute: typeof AppVendasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComprasRoute: AppComprasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFolhaDePagamentoRoute: AppFolhaDePagamentoRoute,
  AppFuncionariosRoute: AppFuncionariosRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppPropriedadesRoute: AppPropriedadesRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVeiculosRoute: AppVeiculosRoute,
  AppVendasRoute: AppVendasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
