/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAcessosRouteImport } from './routes/_authenticated/admin.acessos'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin.empresas'
import { Route as AuthenticatedAdminModulosRouteImport } from './routes/_authenticated/admin.modulos'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin.suporte'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppComprasRouteImport } from './routes/_authenticated/app.compras'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppEmpresasRouteImport } from './routes/_authenticated/app.empresas'
import { Route as AuthenticatedAppEstoqueRouteImport } from './routes/_authenticated/app.estoque'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app.financeiro'
import { Route as AuthenticatedAppFolhaDePagamentoRouteImport } from './routes/_authenticated/app.folha-de-pagamento'
import { Route as AuthenticatedAppFuncionariosRouteImport } from './routes/_authenticated/app.funcionarios'
import { Route as AuthenticatedAppProducaoRouteImport } from './routes/_authenticated/app.producao'
import { Route as AuthenticatedAppPropriedadesRouteImport } from './routes/_authenticated/app.propriedades'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppUsuariosRouteImport } from './routes/_authenticated/app.usuarios'
import { Route as AuthenticatedAppVeiculosRouteImport } from './routes/_authenticated/app.veiculos'
import { Route as AuthenticatedAppVendasRouteImport } from './routes/_authenticated/app.vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAcessosRoute =
  AuthenticatedAdminAcessosRouteImport.update({
    id: '/acessos',
    path: '/acessos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulosRoute =
  AuthenticatedAdminModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComprasRoute = AuthenticatedAppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmpresasRoute =
  AuthenticatedAppEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEstoqueRoute = AuthenticatedAppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFolhaDePagamentoRoute =
  AuthenticatedAppFolhaDePagamentoRouteImport.update({
    id: '/folha-de-pagamento',
    path: '/folha-de-pagamento',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFuncionariosRoute =
  AuthenticatedAppFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProducaoRoute =
  AuthenticatedAppProducaoRouteImport.update({
    id: '/producao',
    path: '/producao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPropriedadesRoute =
  AuthenticatedAppPropriedadesRouteImport.update({
    id: '/propriedades',
    path: '/propriedades',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUsuariosRoute =
  AuthenticatedAppUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVeiculosRoute =
  AuthenticatedAppVeiculosRouteImport.update({
    id: '/veiculos',
    path: '/veiculos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVendasRoute = AuthenticatedAppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/app/compras': typeof AuthenticatedAppComprasRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/empresas': typeof AuthenticatedAppEmpresasRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/folha-de-pagamento': typeof AuthenticatedAppFolhaDePagamentoRoute
  '/app/funcionarios': typeof AuthenticatedAppFuncionariosRoute
  '/app/producao': typeof AuthenticatedAppProducaoRoute
  '/app/propriedades': typeof AuthenticatedAppPropriedadesRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/app/vendas': typeof AuthenticatedAppVendasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/app/compras': typeof AuthenticatedAppComprasRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/empresas': typeof AuthenticatedAppEmpresasRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/folha-de-pagamento': typeof AuthenticatedAppFolhaDePagamentoRoute
  '/app/funcionarios': typeof AuthenticatedAppFuncionariosRoute
  '/app/producao': typeof AuthenticatedAppProducaoRoute
  '/app/propriedades': typeof AuthenticatedAppPropriedadesRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/app/vendas': typeof AuthenticatedAppVendasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/app/compras': typeof AuthenticatedAppComprasRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/empresas': typeof AuthenticatedAppEmpresasRoute
  '/_authenticated/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/folha-de-pagamento': typeof AuthenticatedAppFolhaDePagamentoRoute
  '/_authenticated/app/funcionarios': typeof AuthenticatedAppFuncionariosRoute
  '/_authenticated/app/producao': typeof AuthenticatedAppProducaoRoute
  '/_authenticated/app/propriedades': typeof AuthenticatedAppPropriedadesRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/_authenticated/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/_authenticated/app/vendas': typeof AuthenticatedAppVendasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/acessos'
    | '/admin/empresas'
    | '/admin/modulos'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/folha-de-pagamento'
    | '/app/funcionarios'
    | '/app/producao'
    | '/app/propriedades'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app/vendas'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/acessos'
    | '/admin/empresas'
    | '/admin/modulos'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/empresas'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/folha-de-pagamento'
    | '/app/funcionarios'
    | '/app/producao'
    | '/app/propriedades'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app/vendas'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/acessos'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/modulos'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/app/compras'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/empresas'
    | '/_authenticated/app/estoque'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/folha-de-pagamento'
    | '/_authenticated/app/funcionarios'
    | '/_authenticated/app/producao'
    | '/_authenticated/app/propriedades'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/usuarios'
    | '/_authenticated/app/veiculos'
    | '/_authenticated/app/vendas'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/acessos': {
      id: '/_authenticated/admin/acessos'
      path: '/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AuthenticatedAdminAcessosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modulos': {
      id: '/_authenticated/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AuthenticatedAdminModulosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/compras': {
      id: '/_authenticated/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AuthenticatedAppComprasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/empresas': {
      id: '/_authenticated/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AuthenticatedAppEmpresasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/estoque': {
      id: '/_authenticated/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AuthenticatedAppEstoqueRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/folha-de-pagamento': {
      id: '/_authenticated/app/folha-de-pagamento'
      path: '/folha-de-pagamento'
      fullPath: '/app/folha-de-pagamento'
      preLoaderRoute: typeof AuthenticatedAppFolhaDePagamentoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/funcionarios': {
      id: '/_authenticated/app/funcionarios'
      path: '/funcionarios'
      fullPath: '/app/funcionarios'
      preLoaderRoute: typeof AuthenticatedAppFuncionariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/producao': {
      id: '/_authenticated/app/producao'
      path: '/producao'
      fullPath: '/app/producao'
      preLoaderRoute: typeof AuthenticatedAppProducaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/propriedades': {
      id: '/_authenticated/app/propriedades'
      path: '/propriedades'
      fullPath: '/app/propriedades'
      preLoaderRoute: typeof AuthenticatedAppPropriedadesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/usuarios': {
      id: '/_authenticated/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AuthenticatedAppUsuariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/veiculos': {
      id: '/_authenticated/app/veiculos'
      path: '/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AuthenticatedAppVeiculosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vendas': {
      id: '/_authenticated/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AuthenticatedAppVendasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcessosRoute: typeof AuthenticatedAdminAcessosRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
  AuthenticatedAdminModulosRoute: typeof AuthenticatedAdminModulosRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcessosRoute: AuthenticatedAdminAcessosRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
  AuthenticatedAdminModulosRoute: AuthenticatedAdminModulosRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppComprasRoute: typeof AuthenticatedAppComprasRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppEmpresasRoute: typeof AuthenticatedAppEmpresasRoute
  AuthenticatedAppEstoqueRoute: typeof AuthenticatedAppEstoqueRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppFolhaDePagamentoRoute: typeof AuthenticatedAppFolhaDePagamentoRoute
  AuthenticatedAppFuncionariosRoute: typeof AuthenticatedAppFuncionariosRoute
  AuthenticatedAppProducaoRoute: typeof AuthenticatedAppProducaoRoute
  AuthenticatedAppPropriedadesRoute: typeof AuthenticatedAppPropriedadesRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppUsuariosRoute: typeof AuthenticatedAppUsuariosRoute
  AuthenticatedAppVeiculosRoute: typeof AuthenticatedAppVeiculosRoute
  AuthenticatedAppVendasRoute: typeof AuthenticatedAppVendasRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppComprasRoute: AuthenticatedAppComprasRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppEmpresasRoute: AuthenticatedAppEmpresasRoute,
  AuthenticatedAppEstoqueRoute: AuthenticatedAppEstoqueRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppFolhaDePagamentoRoute: AuthenticatedAppFolhaDePagamentoRoute,
  AuthenticatedAppFuncionariosRoute: AuthenticatedAppFuncionariosRoute,
  AuthenticatedAppProducaoRoute: AuthenticatedAppProducaoRoute,
  AuthenticatedAppPropriedadesRoute: AuthenticatedAppPropriedadesRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppUsuariosRoute: AuthenticatedAppUsuariosRoute,
  AuthenticatedAppVeiculosRoute: AuthenticatedAppVeiculosRoute,
  AuthenticatedAppVendasRoute: AuthenticatedAppVendasRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
